export interface PipelineStep {
  id: string;
  stepNumber: string;
  title: string;
  subtitle: string;
  description: string;
  metric: string;
  metricLabel: string;
  iconName: string;
  // 3D camera target adjustments for this step
  camPos: [number, number, number];
  camFov: number;
  // Where the camera points, in engine-local space — this is what makes each
  // stage feel like it's framing a DIFFERENT PART of the engine, instead of
  // always orbiting the same dead-center point.
  lookAt: [number, number, number];
  // Camera roll (radians) — subtle dutch-angle tilt for cinematic drama.
  camRoll: number;
  rotationOffset: [number, number, number];
  // Subtle engine position offset (x, y, z) — gives each stage a distinct physical perspective
  positionOffset: [number, number, number];
  // Lighting choreography
  ambientIntensity: number;
  spotIntensity: number;
  spotColor: string;
  // Rim light — back edge highlights for premium industrial feel
  rimIntensity: number;
  rimColor: string;
  rimPosition: [number, number, number];
  // Fill light — the cool-toned secondary directional
  fillIntensity: number;
  fillColor: string;
  fillPosition: [number, number, number];
  // Environment & exposure
  envIntensity: number;
  exposure: number;
  // Energy pulse (fires on stage entry)
  pulseIntensity: number;
  pulseColor: string;
  // Which side of the screen the text overlay flies in from for this stage
  labelPosition: 'left' | 'right' | 'top' | 'bottom';
}

export const PIPELINE_STEPS: PipelineStep[] = [
  {
    id: 'intent-classifier',
    stepNumber: '01',
    title: 'Intent Classifier',
    subtitle: 'Neural Query Disambiguation',
    description: 'Parses semantic user intent, classifies query domain, and determines structural query bounds.',
    metric: '< 12ms',
    metricLabel: 'Inference',
    iconName: 'Zap',
    labelPosition: 'left',
    /* WIDE ESTABLISHING SHOT — camera sits back, slightly high, taking in the whole engine */
    camPos: [0, 1.6, 5.0],
    camFov: 40,
    lookAt: [0, 0, 0],
    camRoll: 0,
    rotationOffset: [0, 0, 0],
    positionOffset: [0, 0, 0],
    ambientIntensity: 0.55,
    spotIntensity: 2.5,
    spotColor: '#38bdf8',
    rimIntensity: 1.8,
    rimColor: '#7dd3fc',
    rimPosition: [3.0, 2.0, -5.0],
    fillIntensity: 0.8,
    fillColor: '#bae6fd',
    fillPosition: [-6, -3, -5],
    envIntensity: 0.80,
    exposure: 0.95,
    pulseIntensity: 2.0,
    pulseColor: '#38bdf8',
  },
  {
    id: 'evidence-collector',
    stepNumber: '02',
    title: 'Evidence Collector',
    subtitle: 'Multi-Index Vector Fanout',
    description: 'Simultaneously dispatches queries across dense vector indices, sparse keyword stores, and graph stores.',
    metric: '1024',
    metricLabel: 'Parallel Streams',
    iconName: 'Cpu',
    labelPosition: 'right',
    /* PUSH-IN LEFT — camera swings and dives toward the left intake side, dutch tilt kicks in */
    camPos: [1.5, 1.0, 2.5],
    camFov: 35,
    lookAt: [0.5, 0.2, 0],
    camRoll: -0.05,
    rotationOffset: [0, -0.8, 0],
    positionOffset: [-0.5, 0, 0],
    ambientIntensity: 0.50,
    spotIntensity: 3.5,
    spotColor: '#818cf8',
    rimIntensity: 3.0,
    rimColor: '#a5b4fc',
    rimPosition: [-4.0, 3.0, -4.0],
    fillIntensity: 0.6,
    fillColor: '#c7d2fe',
    fillPosition: [5, 2, -6],
    envIntensity: 0.70,
    exposure: 0.88,
    pulseIntensity: 3.5,
    pulseColor: '#818cf8',
  },
  {
    id: 'entity-extraction',
    stepNumber: '03',
    title: 'Entity Extraction',
    subtitle: 'High-Precision Named Entity Linking',
    description: 'Identifies core concepts, organizations, and domain terms, anchoring them to canonical nodes.',
    metric: '99.4%',
    metricLabel: 'F1 Accuracy',
    iconName: 'Sparkles',
    labelPosition: 'top',
    /* LOW-ANGLE LOOK-UP — camera drops low, tilts up at the top of the block, heroic feel */
    camPos: [0, 4.5, 1.0],
    camFov: 45,
    lookAt: [0, 0.5, -0.5],
    camRoll: 0,
    rotationOffset: [0.6, 0, 0],
    positionOffset: [0, -0.5, 0],
    ambientIntensity: 0.50,
    spotIntensity: 3.8,
    spotColor: '#38bdf8',
    rimIntensity: 3.5,
    rimColor: '#38bdf8',
    rimPosition: [-3.0, 2.0, -5.0],
    fillIntensity: 0.9,
    fillColor: '#bae6fd',
    fillPosition: [-5, -1, -6],
    envIntensity: 0.75,
    exposure: 0.92,
    pulseIntensity: 5.0,
    pulseColor: '#38bdf8',
  },
  {
    id: 'relationship-extraction',
    stepNumber: '04',
    title: 'Relationship Extraction',
    subtitle: 'Triple Formulation & Edge Weighting',
    description: 'Discovers directional connections between entities and computes dynamic confidence weights.',
    metric: '10K+',
    metricLabel: 'Triples / sec',
    iconName: 'GitFork',
    labelPosition: 'bottom',
    /* ORBIT RIGHT — camera sweeps around to the right flank, framing the side linkages */
    camPos: [-2.0, -0.5, 2.5],
    camFov: 38,
    lookAt: [-0.5, 0.2, 0],
    camRoll: 0.04,
    rotationOffset: [0, 1.0, 0],
    positionOffset: [0.5, 0, 0],
    ambientIntensity: 0.65,
    spotIntensity: 4.2,
    spotColor: '#2dd4bf',
    rimIntensity: 4.0,
    rimColor: '#5eead4',
    rimPosition: [4.0, 1.0, -5.0],
    fillIntensity: 1.0,
    fillColor: '#a7f3d0',
    fillPosition: [6, 0, -5],
    envIntensity: 0.80,
    exposure: 0.94,
    pulseIntensity: 6.0,
    pulseColor: '#2dd4bf',
  },
  {
    id: 'knowledge-graph-builder',
    stepNumber: '05',
    title: 'Knowledge Graph Builder',
    subtitle: 'Dynamic Sub-Graph Assembly',
    description: 'Constructs an interactive sub-graph mapping multi-hop inter-dependencies and topic clusters.',
    metric: 'Sub-ms',
    metricLabel: 'Traversal',
    iconName: 'Share2',
    labelPosition: 'left',
    /* EXTREME MACRO — camera all but touches the crankshaft, tightest FOV in the whole sequence */
    camPos: [-1.0, -1.2, 2.0],
    camFov: 40,
    lookAt: [0, 0.5, -0.5],
    camRoll: 0.08,
    rotationOffset: [-0.2, 2.5, 0],
    positionOffset: [0.2, 0.5, 0],
    ambientIntensity: 0.45,
    spotIntensity: 6.0,
    spotColor: '#fbbf24',
    rimIntensity: 5.0,
    rimColor: '#fbbf24',
    rimPosition: [-2.0, -1.0, -6.0],
    fillIntensity: 0.5,
    fillColor: '#fde68a',
    fillPosition: [-3, -4, -5],
    envIntensity: 0.55,
    exposure: 0.82,
    pulseIntensity: 4.0,
    pulseColor: '#fbbf24',
  },
  {
    id: 'evidence-ranking',
    stepNumber: '06',
    title: 'Evidence Ranking',
    subtitle: 'Cross-Encoder Re-Ranking',
    description: 'Evaluates passage relevance using deep cross-attention transformer models to eliminate noise.',
    metric: 'Top-K',
    metricLabel: 'Noise Reduction',
    iconName: 'BarChart2',
    labelPosition: 'right',
    /* HIGH ORBIT — camera rises above and looks down across the top, surveying like a crane shot */
    camPos: [0.8, 0.5, 1.5],
    camFov: 25,
    lookAt: [0.2, 0.2, 0.2],
    camRoll: -0.02,
    rotationOffset: [0.1, 1.2, 0.1],
    positionOffset: [0, 0, 0],
    ambientIntensity: 0.65,
    spotIntensity: 5.5,
    spotColor: '#a78bfa',
    rimIntensity: 4.0,
    rimColor: '#c4b5fd',
    rimPosition: [0.0, 5.0, -4.0],
    fillIntensity: 1.2,
    fillColor: '#e9d5ff',
    fillPosition: [5, 4, -5],
    envIntensity: 0.85,
    exposure: 0.96,
    pulseIntensity: 5.0,
    pulseColor: '#a78bfa',
  },
  {
    id: 'evidence-citations',
    stepNumber: '07',
    title: 'Evidence Citations',
    subtitle: 'Source-Grounded Attribution',
    description: 'Anchors every claim back to its originating passage, preserving a verifiable citation trail.',
    metric: '100%',
    metricLabel: 'Cited Claims',
    iconName: 'Quote',
    labelPosition: 'top',
    /* RIGHT-SIDE PUSH — camera whips to the right and closes in on the exhaust manifold */
    camPos: [-1.8, 2.5, 1.8],
    camFov: 42,
    lookAt: [-0.4, 0.6, 0.2],
    camRoll: 0.03,
    rotationOffset: [0.3, 0.5, 0],
    positionOffset: [0.3, -0.2, 0],
    ambientIntensity: 0.55,
    spotIntensity: 3.5,
    spotColor: '#f472b6',
    rimIntensity: 3.5,
    rimColor: '#f9a8d4',
    rimPosition: [5.0, 2.0, -4.0],
    fillIntensity: 0.7,
    fillColor: '#fecdd3',
    fillPosition: [-4, -2, -6],
    envIntensity: 0.75,
    exposure: 0.90,
    pulseIntensity: 5.5,
    pulseColor: '#f472b6',
  },
  {
    id: 'graph-memory',
    stepNumber: '08',
    title: 'Graph Memory',
    subtitle: 'Persistent Cross-Session Recall',
    description: 'Writes new entities and relationships back into long-term graph memory for future queries.',
    metric: '∞',
    metricLabel: 'Retention',
    iconName: 'Database',
    labelPosition: 'bottom',
    /* WIDE PULL-BACK REVEAL — camera retreats far out, widest FOV in the sequence, engine returns to center */
    camPos: [0, 3.5, 0.2],
    camFov: 30,
    lookAt: [0, 0, 0],
    camRoll: 0,
    rotationOffset: [1.5, 0, 0.5],
    positionOffset: [0, -0.8, 0],
    ambientIntensity: 0.70,
    spotIntensity: 4.0,
    spotColor: '#38bdf8',
    rimIntensity: 4.5,
    rimColor: '#38bdf8',
    rimPosition: [0.0, 3.0, -6.0],
    fillIntensity: 1.1,
    fillColor: '#bae6fd',
    fillPosition: [6, 3, -5],
    envIntensity: 1.00,
    exposure: 1.00,
    pulseIntensity: 7.0,
    pulseColor: '#38bdf8',
  },
  {
    id: 'llm-synthesis',
    stepNumber: '09',
    title: 'LLM Synthesis',
    subtitle: 'Grounded Generation & Verification',
    description: 'Synthesizes verified knowledge into clear, actionable responses strictly grounded in facts.',
    metric: '0.0%',
    metricLabel: 'Hallucination',
    iconName: 'CheckCircle2',
    labelPosition: 'left',
    /* HERO SHOT — elegant final orbit, camera settles dead-center and level for the closing beat */
    camPos: [2.5, 1.2, 4.5],
    camFov: 45,
    lookAt: [0, 0.2, 0],
    camRoll: 0,
    rotationOffset: [0.1, -0.5, 0],
    positionOffset: [-0.2, 0, 0],
    ambientIntensity: 0.65,
    spotIntensity: 6.0,
    spotColor: '#818cf8',
    rimIntensity: 6.0,
    rimColor: '#818cf8',
    rimPosition: [0.0, 4.0, -5.0],
    fillIntensity: 1.0,
    fillColor: '#c7d2fe',
    fillPosition: [5, 3, -5],
    envIntensity: 0.90,
    exposure: 1.02,
    pulseIntensity: 9.0,
    pulseColor: '#818cf8',
  },
];
